services:
  ratestask_web_test:
    build:
      dockerfile: app.Dockerfile
      context: .
    command: python -m pytest -v
    volumes:
      - .:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db
    container_name: ratestask_web_test

  db:
    build:
      context: .
      dockerfile: database.Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ratestask
      POSTGRES_DB: rates
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: ratestask_db
    restart: unless-stopped

volumes:
  postgres_data:
